/// Flutter icons CustomIconFont
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIconFont
///      fonts:
///       - asset: fonts/CustomIconFont.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconFont {
  IconFont._();

  static const _kFontFam = 'CustomIconFont';

  static const IconData person = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData vpn_key = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData insert_link = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData gps_fixed = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData play_arrow = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData konker_icon_white = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData qrcode = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData konker_full = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData info_outline = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData cloud_download = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData cloud_upload = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData format_align_justify = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData flash_off = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData flash_on = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData notifications_off = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData notifications_none = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData stop = const IconData(0xe811, fontFamily: _kFontFam);
}
